# -*- coding: utf-8 -*-
"""linear_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ff_kD1OOvcxtRv2TSOoexjBdSjaYofjj
"""

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import mean_squared_error
from sklearn.linear_model import LinearRegression
from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split, cross_val_score

def load_data():
    """Load the California housing dataset."""
    housing = fetch_california_housing()
    X = housing.data    # features
    y = housing.target  # target variable
    feature_names = housing.feature_names
    return X, y, feature_names

def train_model(X_train, y_train):
    """Train a linear regression model."""
    # TODO: initialize the linear regression model (LinearRegression()) and fit it

    model = LinearRegression()

    model.fit(X_train, y_train)
    return model

def evaluate_model(model, X_test, y_test):
    """Evaluate the trained model on test data."""
    # TODO: evaluate the model on the test data and calculate the MSE

    y_pred = model.predict(X_test)

    mse = mean_squared_error(y_test, y_pred)

    print("Mean Squared Error:", mse)
    return mse

def perform_cross_validation(X_train, y_train):
    """Perform cross-validation to evaluate the model."""
    # TODO: initialize a linear regression model (LinearRegression()) and train it using cross-validation (cross_val_score)
    # Please, use `cv=5` for cross-validation
    model = LinearRegression()

    cv_scores = cross_val_score(model, X_train, y_train, cv=5)

    print("Cross-Validation Scores:", cv_scores)
    print("Mean Cross-Validation Score:", np.mean(cv_scores))
    return cv_scores

def main():
    # Load the data
    X, y, feature_names = load_data()
    df = pd.DataFrame(X, columns=feature_names)
    df["Target"] = y

    # Simple EDA
    print("Basic Statistics:")
    print(df.describe())

    # Correlation Matrix
    plt.figure(figsize=(10, 8))
    sns.heatmap(df.corr(), annot=True, cmap='coolwarm', fmt=".2f")
    plt.title("Correlation Matrix")
    plt.show()

    # Split the data into training and test sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

    # Train the model
    model = train_model(X_train, y_train)

    # Evaluate the model
    mse = evaluate_model(model, X_test, y_test)

    # Perform cross-validation
    cv_scores = perform_cross_validation(X_train, y_train)

main()

